version: "3.9"
services:
  backend:
    image: dockertest_backend
    container_name: backend
    build: ./Backend/
    ports:
      - "8080:8080"
  frontend:
    image: dockertest_frontend
    container_name: frontend
    build: ./Frontend/frontend/
    volumes:
      - ./Frontend/frontend/:/usr/src/nuxt-app
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true 
    depends_on:
      - backend


    